name: Terraform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Check Working Directory
      run: |
        echo "Current directory:"
        pwd
        echo "Listing root contents:"
        ls -l /
      #  echo "Listing contents of /home/runner/work/rakib-tkxel-devops-project/rakib-tkxel-devops-project:"
      #  ls -l /home/runner/work/rakib-tkxel-devops-project/rakib-tkxel-devops-project
        
    - name: Terraform Init
      run: terraform init
      working-directory: terraform-ec2/main.tf
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform-ec2/main.tf
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
